version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
  build:
    commands:
      - echo Build started on `date`
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"backend-repo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json

cache:
  paths:
    - vendor/**/*

