version: 0.2

phases:
  install:
    # runtime-versions:
      # php: 8.1.0
    commands:
      - echo "Installing PHP dependencies..."
      #- composer install --no-interaction --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo "Running migrations or any pre-build tasks if needed"
      - php artisan key:generate
      - php artisan migrate --force

  build:
    commands:
      - echo "Preparing application for deployment..."
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  post_build:
    commands:
      - echo "Running any additional tasks after the build"
      - php artisan test

artifacts:
  files:
    - vendor/**
    - app/**
    - bootstrap/**
    - config/**
    - database/**
    - public/**
    - resources/**
    - routes/**
    - storage/**
    - composer.json
    - composer.lock
    - .env.example
    - artisan

cache:
  paths:
    - vendor/**/*
    - node_modules/**/*
