version: 0.2

phases:
  install:
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install

      - echo Installing phpenv and PHP 8.1...
      - curl -fsSL https://github.com/phpenv/phpenv-installer/raw/master/bin/phpenv-install | bash
      - export PATH="$HOME/.phpenv/bin:$PATH"
      - eval "$(phpenv init -)"
      
      # Ensure php-build is installed and up-to-date
      - git clone https://github.com/php-build/php-build.git ~/.phpenv/plugins/php-build

      # Verify list of available PHP versions
      - phpenv install --list
      
      # Install PHP 8.1
      - phpenv install 8.1
      - phpenv global 8.1
      - phpenv rehash
  build:
    commands:
      - echo Build started on `date`
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"backend-repo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json

cache:
  paths:
    - vendor/**/*
