version: 0.2

phases:
  install:
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-scripts

      - echo Installing phpenv and PHP 8.1.0...
      - curl -fsSL https://github.com/phpenv/phpenv-installer/raw/master/bin/phpenv-install | bash
      - export PATH="$HOME/.phpenv/bin:$PATH"
      - eval "$(phpenv init -)"

      - echo Checking for php-build plugin...
      - |
        if [ ! -d "$HOME/.phpenv/plugins/php-build" ]; then
          git clone https://github.com/php-build/php-build.git ~/.phpenv/plugins/php-build;
        else
          echo "php-build plugin already installed.";
        fi

      - phpenv install 8.1.0
      - phpenv global 8.1.0
      - phpenv rehash

      # Disable OPcache and increase memory limit
      - echo "Disabling OPcache and increasing memory limit..."
      - echo "opcache.enable=0" >> /etc/php.ini
      - echo "zend_extension=opcache.so" >> /etc/php.ini
      - echo "opcache.enable=0" >> /etc/php.d/10-opcache.ini
      - echo "memory_limit = 1G" >> /etc/php.ini

      # Add swap memory
      - sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
      - sudo mkswap /swapfile
      - sudo swapon /swapfile

  build:
    commands:
      - echo Build started on `date`
      - php artisan config:clear
      - php artisan route:clear
      - php artisan view:clear

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"backend-repo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json

cache:
  paths:
    - vendor/**/*
