version: 0.2

phases:
  install:
    commands:
      - echo Installing Composer...
      - composer install

      - echo Checking for PHP 8.1.0...
      - |
        if [ $(php -v | grep -c 'PHP 8.1') -eq 0 ]; then
          echo Installing PHP 8.1.0 via phpenv...
          curl -fsSL https://github.com/phpenv/phpenv-installer/raw/master/bin/phpenv-install | bash
          export PATH="$HOME/.phpenv/bin:$PATH"
          eval "$(phpenv init -)"
          if [ ! -d "$HOME/.phpenv/plugins/php-build" ]; then
            git clone https://github.com/php-build/php-build.git ~/.phpenv/plugins/php-build;
          fi
          phpenv install 8.1.0
          phpenv global 8.1.0
          phpenv rehash
        else
          echo "PHP 8.1 already installed."
        fi

  build:
    commands:
      - echo Build started on `date`
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"backend-repo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json

cache:
  paths:
    - vendor/**/*
