version: 0.2

phases:
  install:
    # runtime-versions:
      # php: 8.1.0
    commands:
      - echo "Installing PHP dependencies..."
      #- composer install --no-interaction --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"backend-repo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json

  build:
    commands:
      - echo "Preparing application for deployment..."
      # - php artisan config:cache
      # - php artisan route:cache
      # - php artisan view:cache

  post_build:
    commands:
      - echo "Running any additional tasks after the build"
      # - php artisan test

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json

cache:
  paths:
    - vendor/**/*

cache:
  paths:
    - vendor/**/*
    - node_modules/**/*
